
package com.sas.xml.schema.sas_svcs.rtdm_1_1.wsdl;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-01-16T10:00:28.726-03:00
 * Generated source version: 2.7.14
 * 
 */
 
public class EventPortType_EventPort_Server{

    protected EventPortType_EventPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new EventPortTypeImpl();
        String address = "http://sasbap.demo.sas.com:8680/RTDM/Event";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new EventPortType_EventPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
