
package com.sas.xml.schema.sas_svcs.rtdm_1_1.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-01-16T10:00:28.710-03:00
 * Generated source version: 2.7.14
 * 
 */
public final class EventPortType_EventPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1/wsdl/", "EventService");

    private EventPortType_EventPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EventService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EventService ss = new EventService(wsdlURL, SERVICE_NAME);
        EventPortType port = ss.getEventPort();  
        
        {
        System.out.println("Invoking event...");
        com.sas.xml.schema.sas_svcs.rtdm_1.EventType _event_parameters = null;
        try {
            com.sas.xml.schema.sas_svcs.rtdm_1.EventResponseType _event__return = port.event(_event_parameters);
            System.out.println("event.result=" + _event__return);

        } catch (FaultException e) { 
            System.out.println("Expected exception: FaultException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
