
package com.sas.xml.schema.sas_svcs.rtdm_1_1.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-01-16T10:00:28.710-03:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "FaultException", targetNamespace = "http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1")
public class FaultException extends Exception {
    
    private com.sas.xml.schema.sas_svcs.rtdm_1.FaultException faultException;

    public FaultException() {
        super();
    }
    
    public FaultException(String message) {
        super(message);
    }
    
    public FaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultException(String message, com.sas.xml.schema.sas_svcs.rtdm_1.FaultException faultException) {
        super(message);
        this.faultException = faultException;
    }

    public FaultException(String message, com.sas.xml.schema.sas_svcs.rtdm_1.FaultException faultException, Throwable cause) {
        super(message, cause);
        this.faultException = faultException;
    }

    public com.sas.xml.schema.sas_svcs.rtdm_1.FaultException getFaultInfo() {
        return this.faultException;
    }
}
